baseURL = "pattenau.de"
languageCode = "en-us"
title = "David Pattenaude"
theme = "hugo-whisper-theme-extended"
themesDir = "themes"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "My Story"
    url = "/story/"
    weight = 2

[[menu.main]]
    name = "My Experience"
    url = "/experience/"
    weight = 3

[[menu.main]]
    name ="Thoughts"
    url = "/thoughts/"
    weight = 4

[[menu.main]]
    name ="Contact"
    url = "/contact/"
    weight = 5

[params]
    mainSections = ["story", "experience", "thoughts", "contact"]
    google_analytics_id=""
    homepage_button_link = "/experience"
    homepage_button_text =  "My Experience"
    homepage_button2_link = "/thoughts"
    homepage_button2_text = "My Thoughts"
    homepage_intro = "Grab some coffee, tea, or a gluten free beer and stay awhile. Learn why I love helping people through my passion for technology."
    homepage_image = ""

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

    [params.homepage_meta_tags]
        meta_description = "Grab some coffee, tea, or a gluten free beer and stay awhile. Learn why I love helping people through my passion for technology."
        meta_og_title = "David Pattenaude"
        meta_og_type = "website"
        meta_og_url = "https://pattenau.de"
        meta_og_image = "/images/tn.png"
        meta_og_description = "Grab some coffee, tea, or a gluten free beer and stay awhile. Learn why I love helping people through my passion for technology."
        meta_twitter_card = "summary"
        meta_twitter_site = "@davidpattenaude"
        meta_twitter_creator = "@davidpattenaude"

    [params.logo]
        mobile = "/images/logo-mobile.svg"
        standard  = "/images/logo.svg"

    [[params.social]]
        title = "GitLab"
        weight = 10
        link = "https://gitlab.com/davidpattenaude"

    [[params.social]]
        title = "GitHub"
        weight = 20
        link = "https://github.com/davidpattenaude"

    [[params.social]]
        title = "LinkedIn"
        weight = 30
        link = "https://linkedin.com/in/davidpattenaude"

    [[params.social]]
        title = "Twitter"
        weight = 40
        link = "https://twitter.com/davidpattenaude"